version: '3.8'

services:
  db:
    image: mysql:8
    container_name: moruku-mysql
    ports:
      - '3306:3306'
    env_file:
      - ./db/.env.dev
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake --general-log=true --general-log-file=/var/log/mysql/mysql.log
    volumes:
      - ./db/conf.d/mysql.conf:/etc/mysql/conf.d/my.cnf:cached
      - ./db/data:/var/lib/mysql:cached
      - ./db/log:/var/log/mysql:cached