#######################################################################
# Spring Boot Built-in
#######################################################################
server:
    port: 8080

#######################################################################
# Spring Datasource Setting
#######################################################################
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/moruku}
        username: ${DATASOURCE_USER:dev_user}
        password: ${DATASOURCE_PASSWORD:dev_user_pass}
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "https://securetoken.google.com/moruku-dev"
                    jwk-set-uri: "https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com"
    jackson:
        date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
        time-zone: "Asia/Tokyo"

#######################################################################
# MyBatis Setting
#######################################################################
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    type-handlers-package: com.morimoto.taichi.moruku.domain.repository.typehandler

#######################################################################
# log Setting
#######################################################################
logging:
    level:
        org:
            springframework:
                security: DEBUG