const getPrefecture = (prefectureId: number) => {
  switch (prefectureId) {
    case 1:
      return "北海道";
    case 2:
      return "青森県";
    case 3:
      return "岩手県";
    case 4:
      return "宮城県";
    case 5:
      return "秋田県";
    case 6:
      return "山形県";
    case 7:
      return "福島県";
    case 8:
      return "茨城県";
    case 9:
      return "栃木県";
    case 10:
      return "群馬県";
    case 11:
      return "埼玉県";
    case 12:
      return "千葉県";
    case 13:
      return "東京都";
    case 14:
      return "神奈川県";
    case 15:
      return "新潟県";
    case 16:
      return "富山県";
    case 17:
      return "石川県";
    case 18:
      return "福井県";
    case 19:
      return "山梨県";
    case 20:
      return "長野県";
    case 21:
      return "岐阜県";
    case 22:
      return "静岡県";
    case 23:
      return "愛知県";
    case 24:
      return "三重県";
    case 25:
      return "滋賀県";
    case 26:
      return "京都府";
    case 27:
      return "大坂府";
    case 28:
      return "兵庫県";
    case 29:
      return "奈良県";
    case 30:
      return "和歌山県";
    case 31:
      return "鳥取県";
    case 32:
      return "島根県";
    case 33:
      return "岡山県";
    case 34:
      return "広島県";
    case 35:
      return "山口県";
    case 36:
      return "徳島県";
    case 37:
      return "香川県";
    case 38:
      return "愛媛県";
    case 39:
      return "高知県";
    case 40:
      return "福岡県";
    case 41:
      return "佐賀県";
    case 42:
      return "長崎県";
    case 43:
      return "熊本県";
    case 44:
      return "大分県";
    case 45:
      return "宮崎県";
    case 46:
      return "鹿児島県";
    case 47:
      return "沖縄県";
    default:
      return "";
  }
};

const getPrefectureId = (prefectureName: string): number | null => {
  switch (prefectureName) {
    case "選択してください":
      return null;
    case "北海道":
      return 1;
    case "青森県":
      return 2;
    case "岩手県":
      return 3;
    case "宮城県":
      return 4;
    case "秋田県":
      return 5;
    case "山形県":
      return 6;
    case "福島県":
      return 7;
    case "茨城県":
      return 8;
    case "栃木県":
      return 9;
    case "群馬県":
      return 10;
    case "埼玉県":
      return 11;
    case "千葉県":
      return 12;
    case "東京都":
      return 13;
    case "神奈川県":
      return 14;
    case "新潟県":
      return 15;
    case "富山県":
      return 16;
    case "石川県":
      return 17;
    case "福井県":
      return 18;
    case "山梨県":
      return 19;
    case "長野県":
      return 20;
    case "岐阜県":
      return 21;
    case "静岡県":
      return 22;
    case "愛知県":
      return 23;
    case "三重県":
      return 24;
    case "滋賀県":
      return 25;
    case "京都府":
      return 26;
    case "大阪府":
      return 27;
    case "兵庫県":
      return 28;
    case "奈良県":
      return 29;
    case "和歌山県":
      return 30;
    case "鳥取県":
      return 31;
    case "島根県":
      return 32;
    case "岡山県":
      return 33;
    case "広島県":
      return 34;
    case "山口県":
      return 35;
    case "徳島県":
      return 36;
    case "香川県":
      return 37;
    case "愛媛県":
      return 38;
    case "高知県":
      return 39;
    case "福岡県":
      return 40;
    case "佐賀県":
      return 41;
    case "長崎県":
      return 42;
    case "熊本県":
      return 43;
    case "大分県":
      return 44;
    case "宮崎県":
      return 45;
    case "鹿児島県":
      return 46;
    case "沖縄県":
      return 47;
    default:
      return null;
  }
};

export {
  getPrefecture,
  getPrefectureId
};